import { HelpCircle, Car, Coins, Gavel, UserX, Ghost, ArrowRight } from 'lucide-react';
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

const CuriosityLab = () => {
    const stories = [
        {
            icon: UserX,
            title: "Amazon's Bias Incident",
            subtitle: "Category: Algorithmic Discrimination",
            description: "Amazon's experimental AI recruiting tool penalized resumes including the word 'women's', revealing deep-seated training data bias. This serves as a foundational case for auditing training sets.",
            color: "text-amber-400",
            bg: "bg-amber-400/5",
            source: "https://www.reuters.com/article/us-amazon-com-jobs-automation-insight-idUSKCN1MK08G"
        },
        {
            icon: Car,
            title: "Tesla 'Phantom Braking'",
            subtitle: "Category: Safety-Critical Systems",
            description: "Documented incidents of autonomous vehicles braking abruptly due to false positives in object detection. Highlighting the critical need for robust sensor fusion and edge-case validation.",
            color: "text-blue-400",
            bg: "bg-blue-400/5",
            source: "https://www.washingtonpost.com/technology/2022/02/02/tesla-phantom-braking/"
        },
        {
            icon: Coins,
            title: "Knight Capital Algorithmic Collapse",
            subtitle: "Category: Financial Instability",
            description: "A $440 million loss in 30 minutes due to an unintended software loop. A landmark case for the necessity of 'circuit breakers' and automated kill-switches in high-frequency AI environments.",
            color: "text-red-400",
            bg: "bg-red-400/5",
            source: "https://www.sec.gov/news/press-release/2013-222"
        },
        {
            icon: Gavel,
            title: "Mata v. Avianca: LLM Hallucinations",
            subtitle: "Category: Legal Reliability",
            description: "Legal filings submitted with non-existent case citations generated by an LLM. This high-profile incident underscores the liability of 'hallucination' in professional services.",
            color: "text-indigo-400",
            bg: "bg-indigo-400/5",
            source: "https://www.reuters.com/legal/transactional/lawyer-used-chatgpt-cite-fake-cases-fined-2023-06-22/"
        },
        {
            icon: Ghost,
            title: "Zillow's Pricing Drift",
            subtitle: "Category: Economic Prediction Errors",
            description: "Zillow's house-pricing algorithm failed to predict inventory volatility, leading to a $300M+ loss. Demonstrating the risks of over-reliance on historical patterns during market shifts.",
            color: "text-emerald-400",
            bg: "bg-emerald-400/5",
            source: "https://www.cnn.com/2021/11/02/homes/zillow-offers-ending/index.html"
        },
        {
            icon: HelpCircle,
            title: "Microsoft's 'Tay' Bot Incident",
            subtitle: "Category: Social Alignment Failure",
            description: "A chatbot that turned offensive within 24 hours due to coordinated manipulation by users. Proving that alignment requires iterative feedback and aggressive safety guardrails.",
            color: "text-purple-400",
            bg: "bg-purple-400/5",
            source: "https://www.theverge.com/2016/3/24/11297050/tay-microsoft-chatbot-racist"
        }
    ];

    return (
        <section className="py-32 bg-[#02020a] relative overflow-hidden">
            <div className="container mx-auto px-6">
                <div className="flex flex-col items-center text-center mb-24">
                    <Badge className="bg-white/5 text-white/50 border-white/10 px-4 py-1.5 text-[9px] font-black uppercase tracking-[0.4em] mb-8">Case Studies: AI Risks</Badge>
                    <h2 className="text-4xl md:text-6xl font-black tracking-tighter uppercase italic text-white/90 mb-8 max-w-4xl">
                        CURIOUS ABOUT THE <br />
                        <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-indigo-600 font-display italic">UNINTENDED.</span>
                    </h2>
                    <p className="text-white/20 text-lg md:text-xl font-light leading-relaxed max-w-2xl">
                        AI failures require careful consideration. Explore potential risk scenarios and understand the importance of proper governance.
                    </p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mb-20">
                    {stories.map((story, i) => (
                        <Card key={i} className="bg-[#080810]/50 border-white/5 p-8 hover:bg-[#0d0d15] hover:border-white/10 transition-all duration-500 group relative overflow-hidden rounded-[32px]">
                            <div className={`absolute top-0 right-0 w-32 h-32 ${story.bg} blur-3xl -mr-16 -mt-16 group-hover:scale-150 transition-transform duration-700`} />

                            <div className="relative z-10">
                                <div className={`w-14 h-14 ${story.bg} rounded-2xl flex items-center justify-center mb-8 border border-white/5 group-hover:scale-110 transition-transform`}>
                                    <story.icon className={`w-6 h-6 ${story.color}`} />
                                </div>
                                <h3 className="text-xl font-black tracking-tight text-white/90 mb-2">{story.title}</h3>
                                <p className={`text-[10px] font-black uppercase tracking-widest ${story.color} mb-6 opacity-60`}>{story.subtitle}</p>
                                <p className="text-sm text-white/30 leading-relaxed font-light mb-8 group-hover:text-white/50 transition-colors">
                                    {story.description}
                                </p>
                                <a
                                    href={story.source}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="flex items-center gap-2 text-[10px] font-black uppercase tracking-widest text-white/20 group-hover:text-blue-400 transition-colors cursor-pointer"
                                >
                                    Case Details <ArrowRight className="w-3 h-3 group-hover:translate-x-1 transition-transform" />
                                </a>
                            </div>
                        </Card>
                    ))}
                </div>

                <div className="flex justify-center">
                    <div className="p-8 bg-[#0d0d15] border border-white/5 rounded-[40px] text-center max-w-3xl w-full relative group cursor-pointer overflow-hidden">
                        <div className="absolute inset-0 bg-blue-600/5 opacity-0 group-hover:opacity-100 transition-opacity" />
                        <p className="text-[10px] font-black uppercase tracking-[0.4em] text-white/20 mb-4 italic">Vision: Responsible AI Future</p>
                        <h4 className="text-xl md:text-2xl font-black tracking-tight text-white mb-6">
                            Interested in learning more about AI risk scenarios?
                        </h4>
                        <p className="text-sm text-white/40 mb-8 leading-relaxed max-w-xl mx-auto">
                            Our research team studies these scenarios to help organizations build safer AI systems.
                        </p>
                        <div className="inline-flex items-center gap-3 px-8 py-4 bg-white text-black rounded-xl text-[11px] font-black uppercase tracking-widest hover:bg-blue-600 hover:text-white transition-all shadow-xl shadow-white/5">
                            Access Full Research Vault
                        </div>
                    </div>
                </div>
            </div>
        </section>
    );
};

export default CuriosityLab;
