import { HelpCircle, Car, Coins, Gavel, UserX, Ghost, ArrowRight } from 'lucide-react';

const CuriosityLab = () => {
    const stories = [
        {
            icon: UserX,
            title: "Amazon's Bias Incident",
            subtitle: "Category: Algorithmic Discrimination",
            description: "Amazon's experimental AI recruiting tool penalized resumes including the word 'women's', revealing deep-seated training data bias. This serves as a foundational case for auditing training sets.",
            color: "text-amber-600",
            bg: "bg-amber-50",
            source: "https://www.reuters.com/article/us-amazon-com-jobs-automation-insight-idUSKCN1MK08G"
        },
        {
            icon: Car,
            title: "Tesla 'Phantom Braking'",
            subtitle: "Category: Safety-Critical Systems",
            description: "Documented incidents of autonomous vehicles braking abruptly due to false positives in object detection. Highlighting the critical need for robust sensor fusion and edge-case validation.",
            color: "text-blue-600",
            bg: "bg-blue-50",
            source: "https://www.washingtonpost.com/technology/2022/02/02/tesla-phantom-braking/"
        },
        {
            icon: Coins,
            title: "Knight Capital Algorithmic Collapse",
            subtitle: "Category: Financial Instability",
            description: "A $440 million loss in 30 minutes due to an unintended software loop. A landmark case for the necessity of 'circuit breakers' and automated kill-switches in high-frequency AI environments.",
            color: "text-red-600",
            bg: "bg-red-50",
            source: "https://www.sec.gov/news/press-release/2013-222"
        },
        {
            icon: Gavel,
            title: "Mata v. Avianca: LLM Hallucinations",
            subtitle: "Category: Legal Reliability",
            description: "Legal filings submitted with non-existent case citations generated by an LLM. This high-profile incident underscores the liability of 'hallucination' in professional services.",
            color: "text-indigo-600",
            bg: "bg-indigo-50",
            source: "https://www.reuters.com/legal/transactional/lawyer-used-chatgpt-cite-fake-cases-fined-2023-06-22/"
        },
        {
            icon: Ghost,
            title: "Zillow's Pricing Drift",
            subtitle: "Category: Economic Prediction Errors",
            description: "Zillow's house-pricing algorithm failed to predict inventory volatility, leading to a $300M+ loss. Demonstrating the risks of over-reliance on historical patterns during market shifts.",
            color: "text-emerald-600",
            bg: "bg-emerald-50",
            source: "https://www.cnn.com/2021/11/02/homes/zillow-offers-ending/index.html"
        }
    ];

    return (
        <section className="py-24 bg-slate-50 border-t border-slate-100">
            <div className="container mx-auto px-6">
                <div className="mb-20 text-center lg:text-left">
                    <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-slate-200/50 border border-slate-200 mb-6">
                        <HelpCircle className="w-3 h-3 text-slate-500" />
                        <span className="text-[9px] font-black uppercase tracking-widest text-slate-500">Baseline Edge Cases</span>
                    </div>
                    <h2 className="text-4xl md:text-6xl font-black tracking-tighter text-slate-900 uppercase italic">CURIOSITY<br /><span className="text-slate-300">HUB.</span></h2>
                    <p className="text-slate-400 text-lg font-light max-w-2xl mt-6">
                        Navigating the boundary of unforeseen model failures to architect more resilient safety protocols.
                    </p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                    {stories.map((story, i) => (
                        <div key={i} className="group relative">
                            <div className="absolute -inset-0.5 bg-gradient-to-tr from-slate-200 to-slate-100 rounded-[32px] opacity-0 group-hover:opacity-100 transition-opacity blur-[2px]" />
                            <div className="relative bg-white border border-slate-100 p-8 rounded-[30px] h-full flex flex-col hover:border-blue-100 transition-all duration-500">
                                <div className={`w-14 h-14 rounded-2xl ${story.bg} flex items-center justify-center mb-8 border border-slate-50`}>
                                    <story.icon className={`w-7 h-7 ${story.color}`} />
                                </div>
                                <div className="text-[10px] font-black uppercase tracking-[0.2em] text-blue-600/50 mb-2">{story.subtitle}</div>
                                <h3 className="text-xl font-black text-slate-900 mb-4 tracking-tight uppercase italic">{story.title}</h3>
                                <p className="text-sm text-slate-400 font-light leading-relaxed mb-8 flex-grow">
                                    {story.description}
                                </p>
                                <a
                                    href={story.source}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-widest text-slate-300 hover:text-blue-600 transition-colors group/link"
                                >
                                    Examine Evidence <ArrowRight className="w-3 h-3 group-hover/link:translate-x-1 transition-transform" />
                                </a>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </section>
    );
};

export default CuriosityLab;
